"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
# ★ NOT unused, and NOT optional. Autogenerated migrations render spatial columns as
# `geoalchemy2.types.Geography(...)` / `Geometry(...)`; without this import the file
# raises NameError at import time and `alembic upgrade head` dies before the first
# statement. This is the single most common PostGIS+Alembic footgun (CONTRACT.md §5.7).
# Leave it here even when a given revision has no spatial column: the next one will.
import geoalchemy2  # noqa: F401
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
